[package]
name = "perceptual-hashing"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
rustdct = "0.7.1"
once_cell = "1.21.3"
rfd = "0.15.3"

[profile.dev.package."*"]
opt-level = 3